GET http://localhost:8080/mvc-app/api/v1/user/all
Authorization: Basic admin admin
###

GET http://localhost:8080/mvc-app/api/v1/user/4/id

###

POST http://localhost:8080/mvc-app/api/v1/user
Content-Type: application/json

{
    "login" : "user",
    "password" : "user"
}

###

PUT http://localhost:8080/mvc-app/api/v1/user
Content-Type: application/json

{
  "id" :3,
  "login" : "user_1",
  "password" : "user_1"
}

###

DELETE http://localhost:8080/mvc-app/api/v1/user/4/id

